import json
import urllib.request
import urllib.error

class OllamaClient:
    def __init__(self, host="http://localhost:11434", model="llama3"):
        self.host = host
        self.model = model
        self.api_url = f"{self.host}/api/generate"

    def generate(self, prompt, system="", format=""):
        data = {
            "model": self.model,
            "prompt": prompt,
            "system": system,
            "stream": False
        }
        if format:
            data["format"] = format

        req = urllib.request.Request(
            self.api_url,
            data=json.dumps(data).encode("utf-8"),
            headers={"Content-Type": "application/json"}
        )

        try:
            with urllib.request.urlopen(req) as response:
                result = json.loads(response.read().decode("utf-8"))
                return result.get("response", "")
        except urllib.error.URLError as e:
            print(f"[OllamaClient] Error connecting to Ollama: {e}")
            return self._mock_response(prompt, format)

    def _mock_response(self, prompt, format):
        """Fallback response if Ollama is unreachable."""
        print("[OllamaClient] Returning mock response due to connection failure.")
        if format == "json":
            if "outline" in prompt.lower() or "director" in prompt.lower() or "story" in prompt.lower():
                return json.dumps({
                    "title": "A Mock Story",
                    "synopsis": "A brave mock hero goes on a mock adventure.",
                    "chapters": [
                        {"chapter_number": 1, "title": "The Mock Beginning", "description": "The hero wakes up."},
                        {"chapter_number": 2, "title": "The Mock Middle", "description": "The hero fights a mock monster."},
                        {"chapter_number": 3, "title": "The Mock End", "description": "The hero returns home mockingly."}
                    ]
                })
            else:
                return json.dumps({"result": "Mock JSON response"})
        return "This is a mock text response generated by the Mock Agent due to missing Ollama connection."
