from fastapi import APIRouter
from pydantic import BaseModel
from typing import Dict, Any

router = APIRouter()

@router.get("/")
async def root():
    return {"message": "Welcome to Omni API - The self-writing API."}

@router.get("/magic/potion")
async def get_magic_potion():
    return {"potion": "Health Potion", "healing": 50, "description": "Restores 50 health points."}

@router.get("/test")
async def get_test():
    return {"message": "Test endpoint generated by Healer."}