import http.server
import socketserver
import json
import threading
import time
import urllib.request
import urllib.error
import uuid
import os

PORT = 8000
OLLAMA_URL = "http://localhost:11434/api/chat"
MODEL = "llama3"

# In-memory state
# nodes: { id: { id, x, y, text, status } } # status: 'pending', 'processed'
# edges: [ { source, target } ]
state = {
    "nodes": {},
    "edges": []
}
state_lock = threading.Lock()

class SynapseHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=os.path.join(os.path.dirname(__file__), "static"), **kwargs)

    def do_GET(self):
        if self.path == '/api/state':
            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            with state_lock:
                self.wfile.write(json.dumps(state).encode('utf-8'))
            return
        return super().do_GET()

    def do_POST(self):
        if self.path == '/api/nodes':
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)
            try:
                data = json.loads(post_data.decode('utf-8'))
                node_id = str(uuid.uuid4())
                new_node = {
                    "id": node_id,
                    "x": data.get("x", 0),
                    "y": data.get("y", 0),
                    "text": data.get("text", ""),
                    "status": "pending"
                }

                with state_lock:
                    state["nodes"][node_id] = new_node

                self.send_response(201)
                self.send_header('Content-type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps(new_node).encode('utf-8'))
            except Exception as e:
                self.send_response(400)
                self.end_headers()
                self.wfile.write(json.dumps({"error": str(e)}).encode('utf-8'))
            return

        elif self.path == '/api/nodes/update':
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)
            try:
                data = json.loads(post_data.decode('utf-8'))
                node_id = data.get("id")

                with state_lock:
                    if node_id in state["nodes"]:
                        if "x" in data: state["nodes"][node_id]["x"] = data["x"]
                        if "y" in data: state["nodes"][node_id]["y"] = data["y"]

                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({"status": "success"}).encode('utf-8'))
            except Exception as e:
                self.send_response(400)
                self.end_headers()
                self.wfile.write(json.dumps({"error": str(e)}).encode('utf-8'))
            return

def ask_ollama(prompt):
    payload = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": "You are an AI assistant that brainstorms related, creative ideas based on a given thought. Respond with a single short, punchy idea. No pleasantries, no markdown."},
            {"role": "user", "content": prompt}
        ],
        "stream": False
    }

    req = urllib.request.Request(OLLAMA_URL, data=json.dumps(payload).encode('utf-8'), headers={'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req, timeout=10) as response:
            result = json.loads(response.read().decode('utf-8'))
            return result.get("message", {}).get("content", "").strip()
    except Exception as e:
        print(f"Ollama error: {e}")
        return None

def thought_weaver_loop():
    while True:
        time.sleep(2)
        node_to_process = None

        with state_lock:
            for node_id, node in state["nodes"].items():
                if node["status"] == "pending":
                    node_to_process = dict(node)
                    state["nodes"][node_id]["status"] = "processing"
                    break

        if node_to_process:
            print(f"Processing node: {node_to_process['text']}")
            idea = ask_ollama(node_to_process['text'])

            if idea:
                new_id = str(uuid.uuid4())
                new_node = {
                    "id": new_id,
                    "x": node_to_process["x"] + 200,
                    "y": node_to_process["y"] + (100 if len(state["nodes"]) % 2 == 0 else -100),
                    "text": idea,
                    "status": "processed" # New nodes generated by AI don't get processed further to avoid infinite loops, or could be 'pending' for recursive! Let's keep it 'processed' for now.
                }

                with state_lock:
                    state["nodes"][new_id] = new_node
                    state["edges"].append({
                        "source": node_to_process["id"],
                        "target": new_id
                    })
                    state["nodes"][node_to_process["id"]]["status"] = "processed"
            else:
                 with state_lock:
                    state["nodes"][node_to_process["id"]]["status"] = "pending" # Retry later if failed

def run_server():
    with socketserver.TCPServer(("", PORT), SynapseHandler) as httpd:
        print(f"Serving at port {PORT}")
        httpd.serve_forever()

if __name__ == '__main__':
    weaver_thread = threading.Thread(target=thought_weaver_loop, daemon=True)
    weaver_thread.start()

    server_thread = threading.Thread(target=run_server, daemon=True)
    server_thread.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("Shutting down...")
